app.xilogravura.path: "./"

info.app:
  name: @project.name@
  description: @project.description@
  version: @project.version@
  encoding: @project.build.sourceEncoding@
  java.version: @java.version@

spring:
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: none